sudo: required
services:
  - docker

before_install:
  - docker build -t abbas/docker-react -f Dockerfile.dev .

script:
  - docker run abbas/docker-react npm run test -- --coverage  

deploy:
  provider: elasticeanstalk
  region: "us-west-2"
  app: "mydocker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306029323"
  bucket_path: "mydocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECURE_KEY"  